-- ============================================================
-- Lote inglês seguro (2026-09-28): 9 obras / 12 volumes do Gutenberg
-- Tradutor morto há 70+ anos pela regra brasileira; base legal de cada
-- obra em server/texts/catalog_2026-09-28_lote-ingles.json e no bloco de
-- proveniência de cada texto. Gerado do catálogo (mesmos slugs e
-- caminhos dos .md já divididos em capítulos por chapterize_texts.py).
-- Por SQL, e não pelo import_pipeline.py: fora do DRY_RUN o pipeline
-- baixa de novo e SOBRESCREVE os .md, desfazendo os capítulos.
-- Rodar DEPOIS de add_credos_ecumenicos (cria o autor igreja-antiga).
-- ============================================================

BEGIN;

INSERT INTO authors (slug, name, birth_year, death_year, bio_summary, denomination_or_tradition) VALUES
  ('hipolito-de-roma', 'Hipólito de Roma', 170, 235, 'Presbítero e teólogo da Igreja de Roma no início do séc. III, morto no exílio na Sardenha. A Tradição Apostólica atribuída a ele é uma das fontes mais antigas sobre a liturgia e a ordem da Igreja.', ARRAY['Patrística', 'Pais Latinos']),
  ('sao-joao-crisostomo', 'São João Crisóstomo', 347, 407, 'Pregador de Antioquia e arcebispo de Constantinopla, chamado Crisóstomo, “boca de ouro”, pela eloquência. Seus sermões e comentários bíblicos estão entre os mais lidos da Igreja grega. Morreu no exílio.', ARRAY['Patrística', 'Pais Gregos']),
  ('sao-bernardo-de-claraval', 'São Bernardo de Claraval', 1090, 1153, 'Abade cisterciense de Claraval, pregador e escritor místico, uma das vozes mais influentes da Igreja do séc. XII.', ARRAY['Medieval', 'Cisterciense']),
  ('philipp-melanchthon', 'Philipp Melanchthon', 1497, 1560, 'Humanista e reformador de Wittenberg, colaborador próximo de Lutero. Redigiu a Confissão de Augsburgo (1530) e sua Apologia (1531).', ARRAY['Reforma', 'Luteranismo']),
  ('richard-baxter', 'Richard Baxter', 1615, 1691, 'Pastor puritano inglês, conhecido pelo ministério em Kidderminster e por obras devocionais e pastorais como The Saints'' Everlasting Rest e The Reformed Pastor.', ARRAY['Puritanos', 'Reforma Inglesa'])
ON CONFLICT (slug) DO NOTHING;

INSERT INTO books (title, author_id, language, description, slug, original_title, publication_year_original, publication_year_translation, translator, original_languages, categories, tags, online_read_path, license_type) VALUES
  ('The Teaching of the Twelve Apostles (Didache)', (SELECT id FROM authors WHERE slug = 'igreja-antiga'), 'Inglês', 'O mais antigo manual de vida cristã e de ordem da Igreja que chegou até nós, redescoberto em 1873 num manuscrito de Constantinopla. Instruções sobre os dois caminhos, o batismo, o jejum, a oração do Pai Nosso, a Ceia e os ministros. Edição de 1884 com o texto grego e tradução inglesa.', 'the-teaching-of-the-twelve-apostles-didache', 'Διδαχὴ τῶν δώδεκα ἀποστόλων', 'c. 50–120', 1884, 'Roswell D. Hitchcock (1817–1887) e Francis Brown (1849–1916)', ARRAY['Grego'], ARRAY['Patrística', 'Liturgia', 'Clássicos'], ARRAY['didaque', 'pais-apostolicos', 'batismo', 'ceia'], '/texts/the-teaching-of-the-twelve-apostles-didache.md', 'public-domain'),
  ('The Apostolic Tradition of Hippolytus', (SELECT id FROM authors WHERE slug = 'hipolito-de-roma'), 'Inglês', 'Ordem da Igreja de Roma no início do séc. III: ordenações, catecumenato, batismo, eucaristia e oração diária. Uma das fontes mais antigas sobre a liturgia cristã. Tradução inglesa de Burton Scott Easton, com introdução e notas.', 'the-apostolic-tradition-of-hippolytus', 'Ἀποστολικὴ παράδοσις', 'c. 215', 1934, 'Burton Scott Easton (1877–1950)', ARRAY['Grego', 'Latim'], ARRAY['Patrística', 'Liturgia', 'Clássicos'], ARRAY['hipolito', 'liturgia', 'batismo', 'igreja-primitiva'], '/texts/the-apostolic-tradition-of-hippolytus.md', 'public-domain'),
  ('Leaves from St. John Chrysostom', (SELECT id FROM authors WHERE slug = 'sao-joao-crisostomo'), 'Inglês', 'Seleção de trechos dos sermões e comentários bíblicos de João Crisóstomo, arcebispo de Constantinopla e o maior pregador da Igreja grega. Tradução de Mary H. Allies.', 'leaves-from-st-john-chrysostom', 'Leaves from St. John Chrysostom', 'séc. IV', 1889, 'Mary H. Allies (1852–1927)', ARRAY['Grego'], ARRAY['Patrística', 'Sermões', 'Clássicos'], ARRAY['crisostomo', 'pais-gregos', 'pregacao'], '/texts/leaves-from-st-john-chrysostom.md', 'public-domain'),
  ('St. Bernard of Clairvaux''s Life of St. Malachy of Armagh', (SELECT id FROM authors WHERE slug = 'sao-bernardo-de-claraval'), 'Inglês', 'Biografia de Malaquias, arcebispo de Armagh e reformador da Igreja na Irlanda, escrita por seu amigo Bernardo de Claraval. Tradução e notas de H. J. Lawlor (SPCK, 1920).', 'st-bernard-of-clairvauxs-life-of-st-malachy-of-armagh', 'Vita sancti Malachiae', 'c. 1149', 1920, 'Hugh Jackson Lawlor (1860–1938)', ARRAY['Latim'], ARRAY['Medieval', 'Hagiografia', 'História da Igreja'], ARRAY['bernardo', 'irlanda', 'cistercienses'], '/texts/st-bernard-of-clairvauxs-life-of-st-malachy-of-armagh.md', 'public-domain'),
  ('Summa Theologica, Part I (Prima Pars)', (SELECT id FROM authors WHERE slug = 'sao-tomas-de-aquino'), 'Inglês', 'Primeira parte da Suma Teológica: Deus, a Trindade, a criação, os anjos e o homem. Tradução inglesa completa dos Padres da Província Dominicana Inglesa (Benziger Brothers).', 'summa-theologica-part-i-prima-pars', 'Summa Theologiae, Prima Pars', '1265–1274', 1911, 'Laurence Shapcote OP (1864–1947), publicada como “Fathers of the English Dominican Province”', ARRAY['Latim'], ARRAY['Escolástica', 'Teologia Sistemática', 'Clássicos'], ARRAY['tomas-de-aquino', 'suma', 'trindade', 'criacao'], '/texts/summa-theologica-part-i-prima-pars.md', 'public-domain'),
  ('Summa Theologica, Part I-II (Pars Prima Secundae)', (SELECT id FROM authors WHERE slug = 'sao-tomas-de-aquino'), 'Inglês', 'Primeira seção da segunda parte da Suma Teológica: o fim último do homem, os atos humanos, as paixões, os hábitos, as virtudes, o pecado, a lei e a graça.', 'summa-theologica-part-i-ii-pars-prima-secundae', 'Summa Theologiae, Prima Secundae', '1265–1274', 1911, 'Laurence Shapcote OP (1864–1947), publicada como “Fathers of the English Dominican Province”', ARRAY['Latim'], ARRAY['Escolástica', 'Teologia Moral', 'Clássicos'], ARRAY['tomas-de-aquino', 'suma', 'lei', 'graca', 'virtudes'], '/texts/summa-theologica-part-i-ii-pars-prima-secundae.md', 'public-domain'),
  ('Summa Theologica, Part II-II (Secunda Secundae)', (SELECT id FROM authors WHERE slug = 'sao-tomas-de-aquino'), 'Inglês', 'Segunda seção da segunda parte da Suma Teológica: as virtudes teologais (fé, esperança, caridade) e cardeais em particular, e os estados de vida.', 'summa-theologica-part-ii-ii-secunda-secundae', 'Summa Theologiae, Secunda Secundae', '1265–1274', 1911, 'Laurence Shapcote OP (1864–1947), publicada como “Fathers of the English Dominican Province”', ARRAY['Latim'], ARRAY['Escolástica', 'Teologia Moral', 'Clássicos'], ARRAY['tomas-de-aquino', 'suma', 'fe', 'caridade', 'virtudes'], '/texts/summa-theologica-part-ii-ii-secunda-secundae.md', 'public-domain'),
  ('Summa Theologica, Part III (Tertia Pars)', (SELECT id FROM authors WHERE slug = 'sao-tomas-de-aquino'), 'Inglês', 'Terceira parte da Suma Teológica: a encarnação, a vida de Cristo e os sacramentos. Tomás morreu antes de concluí-la.', 'summa-theologica-part-iii-tertia-pars', 'Summa Theologiae, Tertia Pars', '1265–1274', 1911, 'Laurence Shapcote OP (1864–1947), publicada como “Fathers of the English Dominican Province”', ARRAY['Latim'], ARRAY['Escolástica', 'Cristologia', 'Clássicos'], ARRAY['tomas-de-aquino', 'suma', 'encarnacao', 'sacramentos'], '/texts/summa-theologica-part-iii-tertia-pars.md', 'public-domain'),
  ('On Prayer and the Contemplative Life', (SELECT id FROM authors WHERE slug = 'sao-tomas-de-aquino'), 'Inglês', 'Os artigos de Tomás de Aquino sobre a oração, a devoção e a vida contemplativa, reunidos e traduzidos por Hugh Pope.', 'on-prayer-and-the-contemplative-life', 'Summa Theologiae (seleção sobre oração e vida contemplativa)', '1265–1274', 1914, 'Hugh Pope OP (1869–1946)', ARRAY['Latim'], ARRAY['Escolástica', 'Espiritualidade', 'Clássicos'], ARRAY['tomas-de-aquino', 'oracao', 'contemplacao'], '/texts/on-prayer-and-the-contemplative-life.md', 'public-domain'),
  ('Commentary on the Epistle to the Galatians', (SELECT id FROM authors WHERE slug = 'martinho-lutero'), 'Inglês', 'O comentário de Lutero à carta aos Gálatas (1535), a exposição mais madura da justificação pela fé. Versão inglesa abreviada de Theodore Graebner (Zondervan, fim dos anos 1930).', 'commentary-on-the-epistle-to-the-galatians', 'In epistolam S. Pauli ad Galatas commentarius', '1535', NULL, 'Theodore Graebner (1876–1950)', ARRAY['Latim'], ARRAY['Reforma', 'Comentário Bíblico', 'Clássicos'], ARRAY['lutero', 'galatas', 'justificacao', 'reforma'], '/texts/commentary-on-the-epistle-to-the-galatians.md', 'public-domain'),
  ('The Apology of the Augsburg Confession', (SELECT id FROM authors WHERE slug = 'philipp-melanchthon'), 'Inglês', 'Defesa da Confissão de Augsburgo escrita por Melanchthon em 1531, em resposta à Confutação católica. Parte do Livro de Concórdia, com o tratamento mais extenso da justificação entre as confissões luteranas.', 'the-apology-of-the-augsburg-confession', 'Apologia Confessionis Augustanae', '1531', 1921, 'F. Bente (1858–1930) e W. H. T. Dau (1864–1944)', ARRAY['Latim', 'Alemão'], ARRAY['Reforma', 'Credos e Confissões', 'Clássicos'], ARRAY['melanchthon', 'augsburgo', 'luteranismo', 'justificacao'], '/texts/the-apology-of-the-augsburg-confession.md', 'public-domain'),
  ('The Saints'' Everlasting Rest', (SELECT id FROM authors WHERE slug = 'richard-baxter'), 'Inglês', 'O clássico devocional puritano sobre o descanso eterno dos santos em Deus e sobre a meditação no céu como disciplina da vida cristã. Na abreviação de Benjamin Fawcett, a forma em que o livro foi mais lido.', 'the-saints-everlasting-rest', 'The Saints'' Everlasting Rest', '1650', NULL, 'Texto original (sem tradução); edição abreviada por Benjamin Fawcett (1715–1780)', ARRAY['Inglês'], ARRAY['Puritanos', 'Literatura Devocional', 'Clássicos'], ARRAY['baxter', 'puritanos', 'ceu', 'meditacao'], '/texts/the-saints-everlasting-rest.md', 'public-domain');

INSERT INTO download_links (book_id, format, url, source)
SELECT b.id, 'html', v.url, 'Project Gutenberg'
FROM books b JOIN (VALUES
  ('the-teaching-of-the-twelve-apostles-didache', 'https://www.gutenberg.org/ebooks/42053'),
  ('the-apostolic-tradition-of-hippolytus', 'https://www.gutenberg.org/ebooks/61614'),
  ('leaves-from-st-john-chrysostom', 'https://www.gutenberg.org/ebooks/62447'),
  ('st-bernard-of-clairvauxs-life-of-st-malachy-of-armagh', 'https://www.gutenberg.org/ebooks/25761'),
  ('summa-theologica-part-i-prima-pars', 'https://www.gutenberg.org/ebooks/17611'),
  ('summa-theologica-part-i-ii-pars-prima-secundae', 'https://www.gutenberg.org/ebooks/17897'),
  ('summa-theologica-part-ii-ii-secunda-secundae', 'https://www.gutenberg.org/ebooks/18755'),
  ('summa-theologica-part-iii-tertia-pars', 'https://www.gutenberg.org/ebooks/19950'),
  ('on-prayer-and-the-contemplative-life', 'https://www.gutenberg.org/ebooks/22295'),
  ('commentary-on-the-epistle-to-the-galatians', 'https://www.gutenberg.org/ebooks/1549'),
  ('the-apology-of-the-augsburg-confession', 'https://www.gutenberg.org/ebooks/6744'),
  ('the-saints-everlasting-rest', 'https://www.gutenberg.org/ebooks/58135')
) AS v(slug, url) ON v.slug = b.slug;

COMMIT;
